### ISSUE TITLE
Wrong bitoffset in the handling of BEQ

### ISSUE THREAD

**Issue by XGZepto** [baichen318/ceng3420#1]
in file `asm.c`,

```
else if (is_opcode(opcode) == BEQ) {
		binary = (0x18 << 2) + 0x03;
		binary += (reg_to_num(arg1, line_no) << 15);
		binary += (reg_to_num(arg2, line_no) << 20);
		int offset;
		offset = label_to_num(arg3, 12, label_table, cmd_no, line_no);
		// imm[11]
		binary += ((offset & 0x800) << 4);
		// imm[4:1]
		binary += ((offset & 0x1E) << 7);
		// imm[10:5]
		binary += ((offset & 0x7E0) << 20);
		// imm[12]
		binary += ((offset & 0x1000) << 19);
	}
```

`imm[11]` should be put in bit 7 instead of 15.

Suggested correction:

```
		// imm[11]
		binary += ((offset & 0x800) >> 4);
```

Please check.

**Comment by XGZepto** [comment]
By the way, we need some clarification on how `label_to_num` is implemented, notably the multiplication of the offset.

- According to [risc-v-asm-manual.pdf](https://github.com/baichen318/ceng3420/blob/main/docs/risc-v-asm-manual.pdf), "the offset is multiplied by 2";
- In Line 102, [asm.c](https://github.com/baichen318/ceng3420/blob/main/asm.c), "so the offset is shifted left with 2";

The behaviour of `label_to_num` caused yet another problem with the handling of `BEQ` (and of course with many other opcodes) since now we should shift the offset right by 1 bit, yet this shift is not executed in [asm.c](https://github.com/baichen318/ceng3420/blob/main/asm.c).

**Comment by baichen318** [comment]
Hi @XGZepto,

Regarding the first question, you are correct.
There is no effect on the released bin files since the correct branch instruction translations (>> 4) generate these bin files.
We directly encode immediate offset values to branch instructions, unconditional jumps, etc. It is different from the specification.

Best regards,
Chen
